services:
  web:
    build: .
    container_name: immortal_poni_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: sh -c "until nc -z redis 6379; do echo waiting for redis; sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000"

  worker:
    build: .
    container_name: immortal_poni_worker
    command: sh -c "until nc -z redis 6379; do echo waiting for redis; sleep 1; done; celery -A app.core.celery:celery_app worker --loglevel=info --concurrency=1"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    build: .
    container_name: immortal_poni_flower
    command: sh -c "until nc -z redis 6379; do echo waiting for redis; sleep 1; done; celery -A app.core.celery:celery_app flower --port=5555 --address=0.0.0.0"
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: immortal_poni_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxclients 2000

volumes:
  redis_data:
