"""auto migration

Revision ID: d6d8f14143f7
Revises: 
Create Date: 2025-02-23 16:14:50.371027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d8f14143f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assign_to', sa.UUID(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assign_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_review_connector',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'review_id')
    )
    with op.batch_alter_table('user_reviews_connector', schema=None) as batch_op:
        batch_op.drop_index('ix_user_reviews_connector_review_id')
        batch_op.drop_index('ix_user_reviews_connector_user_id')

    op.drop_table('user_reviews_connector')
    with op.batch_alter_table('user_skills_connector', schema=None) as batch_op:
        batch_op.drop_index('ix_user_skills_connector_skill_id')
        batch_op.drop_index('ix_user_skills_connector_user_id')
        batch_op.drop_constraint('user_skills_connector_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_skills_connector_skill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_skills', ['skill_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user_skills_connector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_skills_connector_skill_id_fkey', 'user_skills', ['skill_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_skills_connector_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_user_skills_connector_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_skills_connector_skill_id', ['skill_id'], unique=False)

    op.create_table('user_reviews_connector',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='user_reviews_connector_review_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_reviews_connector_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_reviews_connector_pkey')
    )
    with op.batch_alter_table('user_reviews_connector', schema=None) as batch_op:
        batch_op.create_index('ix_user_reviews_connector_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_reviews_connector_review_id', ['review_id'], unique=False)

    op.drop_table('user_review_connector')
    op.drop_table('orders')
    op.drop_table('order_statuses')
    # ### end Alembic commands ###
