name: Deploy to Server

on:
  push:
    branches:
      - Git_Actions_test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/immortal_poni/dockers/immortal_poni
            git pull origin Git_Actions_test
            docker-compose down
            docker system prune -a -f
            docker-compose up -d
